modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "Timefall Development License 1.2" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId = "mcdx" #mandatory
version = "${version}" #mandatory
displayName = "MCDX: A Library" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile="icon.png" #optional
credits="" #optional
authors = "Timefall Development" #optional
description = '''A library for the MCDX Suite of Mods.''' #mandatory (Supports multiline text)

#[[mixins]]
#config = "mcdx.mixins.json"

[[mixins]]
config = "mcdx.neoforge.mixins.json"

[[dependencies.mcdx]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[21.0.167,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.mcdx]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[1.21, 1.22)"
ordering = "NONE"
side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This timefall declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for timefall.
#[features.mcdx]
#openGLVersion="[3.2,)"
